import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Voltaics-25',
  description: 'A real time timer for 24 hours from havoltz club',
  icons: {
    icon: '/favicon.ico', // Path to the favicon in the public folder
  },
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 25d052c9cbacf7ba63288aec3922106392df4f54
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <head>
        <link rel="icon" href="../favicon.ico" type="image/x-icon" />
      </head>
=======
>>>>>>> 25d052c9cbacf7ba63288aec3922106392df4f54
      <body className={inter.className}>{children}</body>
    </html>
  );
}
